{
	"version": 1480393122,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/sprite-sheet0.png",
		"images/background.png",
		"images/ground-sheet0.png",
		"images/bird-sheet0.png",
		"images/tubetop-sheet0.png",
		"images/tubebottom-sheet0.png",
		"images/gameover-sheet0.png",
		"images/nota01-sheet0.png",
		"images/nota02-sheet0.png",
		"images/nota04-sheet0.png",
		"images/cat-sheet0.png",
		"images/cat-sheet1.png",
		"images/dog-sheet0.png",
		"images/dog-sheet1.png",
		"images/dog-sheet2.png",
		"media/foca da meia-noite - sweet child o´ mine.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}